### PR TITLE
dumb cosmic ray rejection 

### PR DESCRIPTION
**Pull request by ajwheeler**
this supercedes #63

### CODE REVIEW

**Comment by ajwheeler** [comment]
This is correct (afaik), but not fast for pixels without CRs.  It is biased for pixels with CRs, and I think I know why, can discuss further.

**Comment by ajwheeler** [comment]
no longer biased.  Needs to be sped up b/c the sigma clipping is stupid slow, but mergable in principle.

**Comment by andrew-saydjari** [comment]
I am merging this because it works to provide us a CR mask, that we can use to both mask bad pixels in 1D and improve calibration stacks, and Adam's time is too valuable to be spent on this. We can come back to this in the future. 
- speed up sigma clipping [should do]
- implement GSPICE CR drop [want to do, but probably not time efficient]
- implement bitmask in flats/dark stacking [Andrew WILL do]

**Comment by ajwheeler** [comment]
I want to note that when I profiled this, it didn't seem like the CR drop branch contributed meaningfully to the runtime, so anyone who wants to do the GSPICE CR drop should verify that it would matter before putting time into it.

**Pull request merged**
