### PR TITLE
Faster woodbury

### PR DESCRIPTION
**Pull request by ajwheeler**

### CODE REVIEW

**Comment by ajwheeler** [comment]
For posterity:

image
image

**Comment by andrew-saydjari** [comment]
Benchmarks on the size of problem we have (H2RGs) with BLAS threads forced to one for Julia (Python case is already single threaded). 
image
image

**Comment by andrew-saydjari** [comment]
That is "TB," just trying to call things names that refer to methods rather than people.

**Comment by ajwheeler** [comment]
Got it.  Should I find it puzzling that the recurse/tb implementation's apparent O(n) performance disappears when one BLAS thread is used?

**Comment by andrew-saydjari** [comment]
No. I think it is still linear at large n. Other differences here include being much larger images than you were testing, which I think changes the low n curvature slightly. I will also note that in order to do this, I pmaped. Which means that several workers were going at once, which can cause to memory controller bottlenecks to appear. But the broad trends you found and order of mag to python remains.

**Comment by andrew-saydjari** [comment]
I will note that large memory pressure is the limit we run in in-practice, which is what motivated me to run this way.

**Comment by ajwheeler** [comment]
The dumb CR rejection here is broken, I am opening a different PR to fix.

**Pull request closed without merging**
