### PR TITLE
SUTR optimization

### PR DESCRIPTION
**Pull request by ajwheeler**

### CODE REVIEW

**Comment by ajwheeler** [comment]
To give a status report on this, I have an implementation that is about 3x faster, BUT I want to try another approach to see if I can do better.  Lmk if this is blocking further progress.

**Comment by andrew-saydjari** [comment]
Nice! Not blocking enough to ask you to stop pursuing even more speed. I can work with the old implementation for the next week or two before it will start to be a real problem.

**Comment by ajwheeler** [comment]
TODO
- [ ] flame graph
- [ ] fix tests
- [ ] try different array axis orderings
- [ ] mask bad diffs

**Comment by ajwheeler** [comment]
After several implementations, and too long spent pondering linear algebra, I came to the conclusion that I could not improve on a refactored and simplified version of Tim's algorithm.  That is what this PR now contains.  It's about 7x faster, and as far as I know, it's ready.  **However, I have not tested it on real data.**

image
<details><summary>here's a flamegraph, but it's not illuminating</summary>
image
</details>

If, at a later point, this is the pipeline bottleneck, I think I can wring more performance from it.  But I'm calling it for now.

**Comment by andrew-saydjari** [comment]
I am going to test this on a sample dark, but will do so after merging... which is terribly form, but will make things easier for me today.

**Comment by andrew-saydjari** [comment]
With respect to building a darkRate image (for APO chip a), this much faster version is delivering results within numerical precision (see difference histogram below).

image

**Comment by andrew-saydjari** [comment]
What was the size of the test that you benchmarked?

**Pull request merged**
