### PR TITLE
SUTR

### PR DESCRIPTION
**Pull request by KevinMcK95**
Translated [Tim Brandt's SUTR python code](https://github.com/t-brandt/fitramp) to Julia and added to `ap3D.jl` and `pipeline.jl`.

### CODE REVIEW

**Review by andrew-saydjari — APPROVED** [review]
With some small formatting changes I added, this looks good to go.

**Comment by andrew-saydjari** [comment]
Question, I see in the ap3D the set up for the CR rejection, but have you/do you intend to actually implement that here?

**Comment by KevinMcK95** [comment]
Haven’t translated the jump/CR detection and removal from Tim’s code yet, but will do that when I’m back from vacation for real.

**Comment by andrew-saydjari** [comment]
Another question, but where are the chi2?

**Comment by KevinMcK95** [comment]
> Another question, but where are the chi2?

Just included now

**Pull request merged**
